# Market Data Agent Configuration
# This file contains the main configuration for the Market Data Agent

# Global settings
environment: development  # development, staging, production
debug: false

# Data source configurations
yfinance:
  enabled: true
  priority: 1  # 1=PRIMARY, 2=SECONDARY, 3=BACKUP
  rate_limit_requests: 120
  rate_limit_period: 3600  # seconds (1 hour)
  timeout: 30
  max_retries: 3
  cache_ttl: 300

alpha_vantage:
  enabled: true
  priority: 2
  api_key: null  # Set via environment variable ALPHA_VANTAGE_API_KEY
  rate_limit_requests: 500
  rate_limit_period: 86400  # seconds (1 day)
  timeout: 30
  max_retries: 3
  cache_ttl: 300

# Source manager configuration
source_manager:
  max_failure_threshold: 5
  circuit_breaker_timeout: 300  # seconds (5 minutes)
  health_check_interval: 60     # seconds (1 minute)
  validation_enabled: true

# Data validation configuration
validation:
  max_price_change_percent: 50.0
  min_volume: 0
  min_price: 0.01
  max_price: 100000.0
  anomaly_detection_enabled: true
  quality_threshold: 70

# API server configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: false  # Set to true for development
  workers: 1
  log_level: "info"
  cors_enabled: true
  cors_origins: ["*"]

# Database configuration
database:
  url: "sqlite:///market_data.db"
  echo: false
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: false
  file_path: "logs/market_data_agent.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5