# TimescaleDB Docker Compose Configuration
# For development and testing of Phase 3 time-series database

version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: market_data_timescale
    restart: unless-stopped

    environment:
      # Database configuration
      POSTGRES_DB: market_data
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: secure_password_2024
      TIMESCALEDB_TELEMETRY: off

      # Performance tuning
      POSTGRES_SHARED_PRELOAD_LIBRARIES: timescaledb
      POSTGRES_MAX_CONNECTIONS: 200
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB

    ports:
      - "5432:5432"

    volumes:
      # Persistent data storage
      - timescale_data:/var/lib/postgresql/data
      # Initialization scripts
      - ./scripts/timescale_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      # Configuration overrides
      - ./scripts/postgresql.conf:/etc/postgresql/postgresql.conf

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U market_user -d market_data"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

  # Redis for Phase 3 Step 2 (caching layer)
  redis:
    image: redis:7-alpine
    container_name: market_data_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data
      - ./scripts/redis.conf:/usr/local/etc/redis/redis.conf

    command: redis-server /usr/local/etc/redis/redis.conf

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: market_data_pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@marketdata.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "8080:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - timescaledb

volumes:
  timescale_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: market_data_network
    driver: bridge