# Ansible Inventory for Market Data Agent
# Phase 4 Step 3: Configuration Management & Environment Automation

all:
  children:
    development:
      children:
        kubernetes_dev:
          hosts:
            k8s-dev-master-1:
              ansible_host: 10.0.1.10
              node_role: master
            k8s-dev-worker-1:
              ansible_host: 10.0.1.11
              node_role: worker
            k8s-dev-worker-2:
              ansible_host: 10.0.1.12
              node_role: worker
          vars:
            environment: dev
            cluster_name: market-data-agent-dev
            kubernetes_version: 1.28.0

        monitoring_dev:
          hosts:
            monitoring-dev-1:
              ansible_host: 10.0.1.20
              monitoring_role: prometheus
            monitoring-dev-2:
              ansible_host: 10.0.1.21
              monitoring_role: grafana
          vars:
            environment: dev

    staging:
      children:
        kubernetes_staging:
          hosts:
            k8s-staging-master-1:
              ansible_host: 10.1.1.10
              node_role: master
            k8s-staging-master-2:
              ansible_host: 10.1.1.11
              node_role: master
            k8s-staging-worker-1:
              ansible_host: 10.1.1.20
              node_role: worker
            k8s-staging-worker-2:
              ansible_host: 10.1.1.21
              node_role: worker
            k8s-staging-worker-3:
              ansible_host: 10.1.1.22
              node_role: worker
          vars:
            environment: staging
            cluster_name: market-data-agent-staging
            kubernetes_version: 1.28.0

        monitoring_staging:
          hosts:
            monitoring-staging-1:
              ansible_host: 10.1.1.30
              monitoring_role: prometheus
            monitoring-staging-2:
              ansible_host: 10.1.1.31
              monitoring_role: grafana
            monitoring-staging-3:
              ansible_host: 10.1.1.32
              monitoring_role: elasticsearch
          vars:
            environment: staging

    production:
      children:
        kubernetes_prod:
          hosts:
            k8s-prod-master-1:
              ansible_host: 10.2.1.10
              node_role: master
            k8s-prod-master-2:
              ansible_host: 10.2.1.11
              node_role: master
            k8s-prod-master-3:
              ansible_host: 10.2.1.12
              node_role: master
            k8s-prod-worker-1:
              ansible_host: 10.2.1.20
              node_role: worker
            k8s-prod-worker-2:
              ansible_host: 10.2.1.21
              node_role: worker
            k8s-prod-worker-3:
              ansible_host: 10.2.1.22
              node_role: worker
            k8s-prod-worker-4:
              ansible_host: 10.2.1.23
              node_role: worker
            k8s-prod-worker-5:
              ansible_host: 10.2.1.24
              node_role: worker
          vars:
            environment: prod
            cluster_name: market-data-agent-prod
            kubernetes_version: 1.28.0

        monitoring_prod:
          hosts:
            monitoring-prod-1:
              ansible_host: 10.2.1.30
              monitoring_role: prometheus
            monitoring-prod-2:
              ansible_host: 10.2.1.31
              monitoring_role: grafana
            monitoring-prod-3:
              ansible_host: 10.2.1.32
              monitoring_role: elasticsearch
            monitoring-prod-4:
              ansible_host: 10.2.1.33
              monitoring_role: elasticsearch
            monitoring-prod-5:
              ansible_host: 10.2.1.34
              monitoring_role: elasticsearch
          vars:
            environment: prod

        database_prod:
          hosts:
            db-prod-1:
              ansible_host: 10.2.1.40
              database_role: primary
            db-prod-2:
              ansible_host: 10.2.1.41
              database_role: replica
          vars:
            environment: prod

  vars:
    # Common variables for all hosts
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/market-data-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    # Project configuration
    project_name: market-data-agent
    project_owner: platform-team

    # Common packages
    common_packages:
      - curl
      - wget
      - git
      - htop
      - vim
      - jq
      - unzip
      - python3
      - python3-pip
      - docker.io
      - awscli

    # Docker configuration
    docker_users:
      - ubuntu

    # Time synchronization
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org

    # Logging configuration
    log_retention_days: 30

    # Security configuration
    ssh_hardening:
      permit_root_login: no
      password_authentication: no
      challenge_response_authentication: no
      use_pam: yes

    # Monitoring configuration
    node_exporter_version: 1.6.1
    prometheus_version: 2.47.0
    grafana_version: 10.1.0