{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "market-data-agent.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "market-data-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database connection
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "market-data-agent.postgresql.url" . | quote }}
  {{- else }}
  database-url: {{ .Values.secrets.database_url | quote }}
  {{- end }}

  # Redis connection
  {{- if .Values.redis.enabled }}
  redis-url: {{ include "market-data-agent.redis.url" . | quote }}
  {{- else }}
  redis-url: {{ .Values.secrets.redis_url | quote }}
  {{- end }}

  # API Keys
  api-keys: {{ .Values.secrets.api_keys | quote }}

  # JWT Secret
  jwt-secret: {{ .Values.secrets.jwt_secret | quote }}

  # Additional secrets can be added here
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "market-data-agent.fullname" . }}-db-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "market-data-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-env
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "market-data-agent.fullname" . }}-redis-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "market-data-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-env
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
{{- end }}
{{- end }}