apiVersion: v1
kind: Service
metadata:
  name: {{ include "market-data-agent.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "market-data-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.websocket }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "market-data-agent.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "market-data-agent.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "market-data-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.ports.metrics | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "market-data-agent.selectorLabels" . | nindent 4 }}
{{- end }}