# Common Role Handlers
# Phase 4 Step 3: Configuration Management & Environment Automation

- name: restart chrony
  systemd:
    name: chrony
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: move helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: yes