apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: analytics-service-kong-ingress
  namespace: kong
spec:
  upstream:
    algorithm: least-connections
    hash_on: none
    hash_fallback: none
    healthchecks:
      active:
        healthy:
          http_statuses:
          - 200
          - 302
          interval: 30
          successes: 3
        http_path: "/health"
        timeout: 10
        unhealthy:
          http_failures: 3
          http_statuses:
          - 429
          - 500
          - 502
          - 503
          - 504
          interval: 10
          tcp_failures: 3
          timeout: 10
      passive:
        healthy:
          http_statuses:
          - 200
          - 201
          - 202
          - 203
          - 204
          - 205
          - 206
          - 300
          - 301
          - 302
          - 303
          - 304
          - 307
          - 308
          successes: 3
        unhealthy:
          http_failures: 3
          http_statuses:
          - 429
          - 500
          - 502
          - 503
          - 504
          tcp_failures: 3
      threshold: 5
  proxy:
    protocol: http
    path: /
    connect_timeout: 15000
    write_timeout: 120000
    read_timeout: 120000
    retries: 3
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
  annotations:
    konghq.com/plugins: rate-limiting-basic,jwt-auth,cors-policy,request-transformer,response-transformer,prometheus-metrics
    consul.hashicorp.com/service-name: "analytics-api"
    consul.hashicorp.com/service-port: "8081"
    consul.hashicorp.com/service-tags: "api,analytics,v1"
    consul.hashicorp.com/service-meta-version: "1.0.0"
    consul.hashicorp.com/service-meta-protocol: "http"
spec:
  type: ExternalName
  externalName: analytics-agent.market-data.svc.cluster.local
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-ingress
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: rate-limiting-basic,jwt-auth,cors-policy,analytics-request-transformer,analytics-response-transformer,prometheus-metrics
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    konghq.com/https-redirect-status-code: "301"
spec:
  rules:
  - host: api.market-data.example.com
    http:
      paths:
      - path: /api/v1/analytics
        pathType: Prefix
        backend:
          service:
            name: analytics-service
            port:
              number: 80
  - host: internal-api.market-data.local
    http:
      paths:
      - path: /api/v1/analytics
        pathType: Prefix
        backend:
          service:
            name: analytics-service
            port:
              number: 80
  tls:
  - hosts:
    - api.market-data.example.com
    secretName: market-data-tls
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: analytics-user
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    consul.hashicorp.com/service-name: "analytics-consumer"
username: analytics-user
custom_id: "analytics-user-consumer"
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: analytics-admin
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: analytics-admin
custom_id: "analytics-admin-consumer"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-user-jwt
  namespace: kong
  labels:
    konghq.com/credential: jwt
    app: market-data-agent
type: Opaque
stringData:
  kongCredType: jwt
  key: "analytics-user-key"
  algorithm: "RS256"
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvJqZvMlrf7tt...
    -----END PUBLIC KEY-----
  secret: "analytics-user-jwt-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-admin-jwt
  namespace: kong
  labels:
    konghq.com/credential: jwt
    app: market-data-agent
type: Opaque
stringData:
  kongCredType: jwt
  key: "analytics-admin-key"
  algorithm: "RS256"
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvJqZvMlrf7tt...
    -----END PUBLIC KEY-----
  secret: "analytics-admin-jwt-secret"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: analytics-request-transformer
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
config:
  add:
    headers:
    - "X-Service:analytics"
    - "X-Version:v1.0.0"
    - "X-Request-ID:$(uuid)"
    - "X-Analytics-Timestamp:$(current_time)"
    querystring:
    - "api_version:v1"
    - "format:json"
  append:
    headers:
    - "X-Correlation-ID:$(uuid)"
  remove:
    headers:
    - "X-Internal-Auth"
    - "X-Debug-Info"
    - "X-Raw-Query"
  replace:
    headers:
    - "User-Agent:Analytics-Gateway/1.0"
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: analytics-response-transformer
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
config:
  add:
    headers:
    - "X-API-Version:v1.0.0"
    - "X-Response-Time:$(response_time)"
    - "X-Upstream-Latency:$(kong_upstream_latency)"
    - "X-Proxy-Latency:$(kong_proxy_latency)"
    - "Cache-Control:private, max-age=60"
    - "X-Analytics-Engine:Market-Data-Analytics/1.0"
    json:
    - "meta.timestamp:$(current_time)"
    - "meta.version:v1.0.0"
    - "meta.request_id:$(request_id)"
  remove:
    headers:
    - "X-Internal-Token"
    - "X-Database-Connection"
    - "X-Query-Plan"
    - "X-Computation-Time"
plugin: response-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: analytics-rate-limiting
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
config:
  minute: 50
  hour: 500
  day: 5000
  policy: redis
  redis_host: redis.market-data.svc.cluster.local
  redis_port: 6379
  redis_password: redis_password
  redis_database: 3
  hide_client_headers: false
  fault_tolerant: true
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: analytics-caching
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
config:
  response_code:
  - 200
  - 301
  - 404
  request_method:
  - GET
  - HEAD
  content_type:
  - application/json
  - text/plain
  cache_ttl: 300
  cache_control: true
  storage_ttl: 600
  strategy: memory
  memory:
    dictionary_name: "kong_db_cache"
plugin: proxy-cache
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: analytics-request-size-limiting
  namespace: kong
  labels:
    app: market-data-agent
    service: analytics
config:
  allowed_payload_size: 16
  size_unit: megabytes
  require_content_length: true
plugin: request-size-limiting