apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: market-data-service-kong-ingress
  namespace: kong
spec:
  upstream:
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    healthchecks:
      active:
        healthy:
          http_statuses:
          - 200
          - 302
          interval: 30
          successes: 3
        http_path: "/health"
        timeout: 10
        unhealthy:
          http_failures: 3
          http_statuses:
          - 429
          - 500
          - 502
          - 503
          - 504
          interval: 10
          tcp_failures: 3
          timeout: 10
      passive:
        healthy:
          http_statuses:
          - 200
          - 201
          - 202
          - 203
          - 204
          - 205
          - 206
          - 300
          - 301
          - 302
          - 303
          - 304
          - 307
          - 308
          successes: 3
        unhealthy:
          http_failures: 3
          http_statuses:
          - 429
          - 500
          - 502
          - 503
          - 504
          tcp_failures: 3
      threshold: 10
  proxy:
    protocol: http
    path: /
    connect_timeout: 10000
    write_timeout: 60000
    read_timeout: 60000
    retries: 5
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  namespace: kong
  labels:
    app: market-data-agent
    service: market-data
  annotations:
    konghq.com/plugins: rate-limiting-premium,jwt-auth,cors-policy,request-transformer,response-transformer,prometheus-metrics
    consul.hashicorp.com/service-name: "market-data-api"
    consul.hashicorp.com/service-port: "8080"
    consul.hashicorp.com/service-tags: "api,market-data,v1"
    consul.hashicorp.com/service-meta-version: "1.0.0"
    consul.hashicorp.com/service-meta-protocol: "http"
spec:
  type: ExternalName
  externalName: market-data-agent.market-data.svc.cluster.local
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: market-data-ingress
  namespace: kong
  labels:
    app: market-data-agent
    service: market-data
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: rate-limiting-premium,jwt-auth,cors-policy,request-transformer,response-transformer,prometheus-metrics
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    konghq.com/https-redirect-status-code: "301"
spec:
  rules:
  - host: api.market-data.example.com
    http:
      paths:
      - path: /api/v1/market-data
        pathType: Prefix
        backend:
          service:
            name: market-data-service
            port:
              number: 80
  - host: internal-api.market-data.local
    http:
      paths:
      - path: /api/v1/market-data
        pathType: Prefix
        backend:
          service:
            name: market-data-service
            port:
              number: 80
  tls:
  - hosts:
    - api.market-data.example.com
    secretName: market-data-tls
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: market-data-internal
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    consul.hashicorp.com/service-name: "market-data-consumer"
username: market-data-internal
custom_id: "internal-service-consumer"
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: market-data-external
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: market-data-external
custom_id: "external-api-consumer"
---
apiVersion: v1
kind: Secret
metadata:
  name: market-data-internal-jwt
  namespace: kong
  labels:
    konghq.com/credential: jwt
    app: market-data-agent
type: Opaque
stringData:
  kongCredType: jwt
  key: "market-data-internal-key"
  algorithm: "RS256"
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvJqZvMlrf7tt...
    -----END PUBLIC KEY-----
  secret: "internal-jwt-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: market-data-external-key
  namespace: kong
  labels:
    konghq.com/credential: key-auth
    app: market-data-agent
type: Opaque
stringData:
  kongCredType: key-auth
  key: "external-api-key-12345"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: market-data-rate-limiting
  namespace: kong
  labels:
    app: market-data-agent
config:
  minute: 500
  hour: 5000
  day: 50000
  policy: redis
  redis_host: redis.market-data.svc.cluster.local
  redis_port: 6379
  redis_password: redis_password
  redis_database: 2
  hide_client_headers: false
  fault_tolerant: true
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: market-data-circuit-breaker
  namespace: kong
  labels:
    app: market-data-agent
config:
  failure_threshold: 10
  recovery_timeout: 30
  success_threshold: 3
  timeout: 5000
plugin: circuit-breaker
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: market-data-request-size-limiting
  namespace: kong
  labels:
    app: market-data-agent
config:
  allowed_payload_size: 8
  size_unit: megabytes
  require_content_length: true
plugin: request-size-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: market-data-request-transformer
  namespace: kong
  labels:
    app: market-data-agent
config:
  add:
    headers:
    - "X-Service:market-data"
    - "X-Version:v1.0.0"
    - "X-Request-ID:$(uuid)"
    - "X-Forwarded-Time:$(current_time)"
    querystring:
    - "api_version:v1"
  append:
    headers:
    - "X-Correlation-ID:$(uuid)"
  remove:
    headers:
    - "X-Internal-Auth"
    - "X-Debug-Info"
  replace:
    headers:
    - "User-Agent:Market-Data-Gateway/1.0"
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: market-data-response-transformer
  namespace: kong
  labels:
    app: market-data-agent
config:
  add:
    headers:
    - "X-API-Version:v1.0.0"
    - "X-Response-Time:$(response_time)"
    - "X-Upstream-Latency:$(kong_upstream_latency)"
    - "X-Proxy-Latency:$(kong_proxy_latency)"
    - "Cache-Control:public, max-age=300"
    json:
    - "meta.timestamp:$(current_time)"
    - "meta.version:v1.0.0"
  remove:
    headers:
    - "X-Internal-Token"
    - "X-Database-Password"
    - "X-Internal-Config"
plugin: response-transformer