# Grafana Data Source Provisioning
# Phase 4 Step 2: Enterprise Monitoring & Observability

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: "30s"
      customQueryParameters: ""
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60s
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    version: 1
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: [{ key: 'service.name', value: 'service' }]
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      nodeGraph:
        enabled: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "market-data-*"
    version: 1
    editable: true
    jsonData:
      index: "market-data-*"
      timeField: "@timestamp"
      esVersion: "7.10.0"
      includeFrozen: false
      logMessageField: "message"
      logLevelField: "level"
      interval: "Daily"
      maxConcurrentShardRequests: 5
      queryTimeout: "60s"