apiVersion: v1
kind: ConfigMap
metadata:
  name: market-data-agent-config
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
data:
  # Application configuration
  APP_NAME: "market-data-agent"
  APP_VERSION: "1.0.0"

  # Server configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  WEBSOCKET_PORT: "8001"
  METRICS_PORT: "8080"

  # Workers configuration
  WORKERS: "4"
  WORKER_CLASS: "uvicorn.workers.UvicornWorker"

  # Database configuration
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"

  # Cache configuration
  CACHE_TTL: "300"
  CACHE_MAX_SIZE: "10000"

  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_WINDOW: "60"

  # Monitoring
  PROMETHEUS_ENABLED: "true"
  PROMETHEUS_PORT: "8080"
  PROMETHEUS_PATH: "/metrics"

  # Logging
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"
  LOG_FILE: "/app/logs/app.log"

  # Health checks
  HEALTH_CHECK_TIMEOUT: "5"
  HEALTH_CHECK_INTERVAL: "30"

  # Data sources
  DATA_SOURCES_ENABLED: "yfinance,alpha_vantage,iex_cloud,twelve_data,finnhub,polygon"

  # Quality settings
  QUALITY_THRESHOLD: "0.8"
  QUALITY_WINDOW: "3600"

  # Memory settings
  MEMORY_CLEANUP_INTERVAL: "3600"
  MEMORY_MAX_ENTITIES: "10000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-data-agent-app-config
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
data:
  production.yaml: |
    # Market Data Agent Production Configuration
    app:
      name: market-data-agent
      version: "1.0.0"
      environment: production
      debug: false

    server:
      host: "0.0.0.0"
      port: 8000
      websocket_port: 8001
      metrics_port: 8080
      workers: 4
      worker_class: "uvicorn.workers.UvicornWorker"

    database:
      pool_size: 20
      max_overflow: 30
      pool_timeout: 30
      echo: false
      pool_pre_ping: true

    cache:
      enabled: true
      ttl: 300
      max_size: 10000
      compression: true

    monitoring:
      prometheus:
        enabled: true
        port: 8080
        path: "/metrics"
      health_checks:
        timeout: 5
        interval: 30

    logging:
      level: INFO
      format: json
      file: "/app/logs/app.log"
      rotation: "1 day"
      retention: "30 days"

    data_sources:
      yfinance:
        enabled: true
        priority: 1
        rate_limit: 120
      alpha_vantage:
        enabled: true
        priority: 2
        rate_limit: 500
      iex_cloud:
        enabled: true
        priority: 3
        rate_limit: 500000
      twelve_data:
        enabled: true
        priority: 4
        rate_limit: 800
      finnhub:
        enabled: true
        priority: 5
        rate_limit: 3600
      polygon:
        enabled: true
        priority: 6
        rate_limit: 5

    quality:
      threshold: 0.8
      window: 3600
      scoring:
        weights:
          completeness: 0.2
          accuracy: 0.25
          consistency: 0.2
          timeliness: 0.15
          validity: 0.1
          uniqueness: 0.1

    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst_size: 100
      algorithm: "token_bucket"