apiVersion: v1
kind: ServiceAccount
metadata:
  name: market-data-agent
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: market-data-agent
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: market-data-agent
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
subjects:
- kind: ServiceAccount
  name: market-data-agent
  namespace: market-data-agent
roleRef:
  kind: Role
  name: market-data-agent
  apiGroup: rbac.authorization.k8s.io