apiVersion: v1
kind: Service
metadata:
  name: market-data-agent-api
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 8001
    targetPort: websocket
    protocol: TCP
  selector:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-agent-metrics
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-agent-headless
  namespace: market-data-agent
  labels:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: market-data-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: market-data-agent
    app.kubernetes.io/component: api